trivia:
    associations:
        0: "Application has_many questions TriviaQuestion"
        1: "User has_many answers TriviaAnswer"
        2: "Application has_many answers TriviaAnswer"
        3: "User has_many user_summaries TriviaUserSummary"
        4: "Application has_many user_summaries TriviaUserSummary" 
    perms: ""
    secondary_perms:
        enter: "public_profile, publish_actions"
        mobile: "public_profile, publish_actions"
        form: "public_profile, public_profile"
    status: :public
photo_contest:
    associations:
        0: "Application has_many photos PhotoContestPhoto"
        1: "User has_many photos PhotoContestPhoto"
        2: "Application has_many votes PhotoContestVote"
        3: "User has_many votes PhotoContestVote"
    perms: ""
    secondary_perms:
        enter: "email, user_friends"
        form: "email, user_friends"
    status: :public
top_fans:
    perms: ""
    secondary_perms:
        enter: "email, user_friends"
        form: "email, user_friends"
    status: :public