trivia:
    associations:
        0: "Application has_many questions TriviaQuestion"
        1: "User has_many answers TriviaAnswer"
        2: "Application has_many answers TriviaAnswer"
        3: "User has_many user_summaries TriviaUserSummary"
        4: "Application has_many user_summaries TriviaUserSummary" 
photo_contest:
    associations:
        0: "Application has_many photos PhotoContestPhoto"
        1: "User has_many photos PhotoContestPhoto"
        2: "Application has_many votes PhotoContestVote"
        3: "User has_many votes PhotoContestVote"
top_fans:
memory_match:
    associations:
        0: "Application has_many cards MemoryMatchCard"
        1: "Application has_many entries MemoryMatchEntry"
        2: "FbUser has_one entry MemoryMatchEntry"