# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0990027a0ea280e3d0e98d7bb717bdef1ed0e6c414f483000f4cc0f167e8e9cffd03371f647db71eeabd1690cdc7d784883a7400f3b419f7c77ff0e14e607150

test:
  secret_key_base: 9c9fe2ce63e2795400dbb2e94fcbcaeed8a6b5e309b1d91324924d5c41cc803001a6538dd94135aa065c3fd30a6a185354b12aa3f3b1251cd122ebc1ca9ef322

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
